// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: exemploGC.flex


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
class Yylex {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\u10ff\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\0\1\3\22\0\1\1\1\4"+
    "\1\5\1\0\1\6\1\7\1\10\1\0\6\7\1\0"+
    "\1\7\12\11\1\0\1\7\1\12\1\13\1\14\2\0"+
    "\1\15\1\16\1\17\1\16\1\20\1\21\6\16\1\22"+
    "\1\23\1\24\2\16\1\25\1\26\1\27\6\16\1\7"+
    "\1\0\1\7\1\0\1\30\1\0\1\31\1\32\1\33"+
    "\1\34\1\35\1\36\1\16\1\37\1\40\1\16\1\41"+
    "\1\42\1\43\1\44\1\45\2\16\1\46\1\47\1\50"+
    "\1\51\1\52\1\53\3\16\1\7\1\54\1\7\u0182\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[512];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\2\3\1\4\2\1\1\4\1\1"+
    "\1\5\3\4\13\6\1\1\1\7\3\0\1\10\1\11"+
    "\1\12\1\13\7\6\1\14\7\6\1\15\1\16\2\0"+
    "\6\6\1\17\1\20\6\6\2\0\1\21\2\6\1\22"+
    "\2\6\1\23\1\24\1\25\1\26\2\6\2\0\1\27"+
    "\1\6\1\30\1\31\1\32\1\33\2\0\1\6\2\0"+
    "\1\6\2\0\1\34\2\0\1\35\1\36\1\37";

  private static int [] zzUnpackAction() {
    int [] result = new int[103];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\55\0\132\0\55\0\207\0\264\0\341\0\u010e"+
    "\0\55\0\u013b\0\u0168\0\u0195\0\u01c2\0\u01ef\0\u021c\0\u0249"+
    "\0\u0276\0\u02a3\0\u02d0\0\u02fd\0\u032a\0\u0357\0\u0384\0\u03b1"+
    "\0\u03de\0\u040b\0\55\0\u0438\0\u0465\0\u0492\0\55\0\55"+
    "\0\55\0\55\0\u04bf\0\u04ec\0\u0519\0\u0546\0\u0573\0\u05a0"+
    "\0\u05cd\0\u021c\0\u05fa\0\u0627\0\u0654\0\u0681\0\u06ae\0\u06db"+
    "\0\u0708\0\55\0\u0438\0\u0735\0\u0762\0\u078f\0\u07bc\0\u07e9"+
    "\0\u0816\0\u0843\0\u0870\0\u021c\0\u021c\0\u089d\0\u08ca\0\u08f7"+
    "\0\u0924\0\u0951\0\u097e\0\u09ab\0\u09d8\0\u021c\0\u0a05\0\u0a32"+
    "\0\u021c\0\u0a5f\0\u0a8c\0\u021c\0\u021c\0\u021c\0\u021c\0\u0ab9"+
    "\0\u0ae6\0\u0b13\0\u0b40\0\u021c\0\u0b6d\0\u021c\0\u021c\0\u021c"+
    "\0\u021c\0\u0b9a\0\u0bc7\0\u0bf4\0\u0c21\0\u0c4e\0\u0c7b\0\u0ca8"+
    "\0\u0cd5\0\u021c\0\u0d02\0\u0d2f\0\55\0\55\0\55";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[103];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\13\17\1\2\1\17"+
    "\1\20\1\21\1\17\1\22\1\23\1\17\1\24\2\17"+
    "\1\25\2\17\1\26\1\17\1\27\1\17\1\30\1\31"+
    "\1\32\56\0\1\3\55\0\1\4\65\0\1\33\41\0"+
    "\2\34\1\0\52\34\22\0\1\35\4\0\1\36\35\0"+
    "\1\37\55\0\1\13\56\0\1\40\54\0\1\41\54\0"+
    "\1\42\52\0\1\17\3\0\13\17\1\0\23\17\12\0"+
    "\1\17\3\0\13\17\1\0\14\17\1\43\1\44\5\17"+
    "\12\0\1\17\3\0\13\17\1\0\14\17\1\45\6\17"+
    "\12\0\1\17\3\0\13\17\1\0\11\17\1\46\11\17"+
    "\12\0\1\17\3\0\13\17\1\0\1\47\10\17\1\50"+
    "\2\17\1\51\6\17\12\0\1\17\3\0\13\17\1\0"+
    "\5\17\1\52\5\17\1\53\7\17\12\0\1\17\3\0"+
    "\13\17\1\0\1\54\22\17\12\0\1\17\3\0\13\17"+
    "\1\0\4\17\1\55\16\17\12\0\1\17\3\0\13\17"+
    "\1\0\15\17\1\56\5\17\12\0\1\17\3\0\13\17"+
    "\1\0\14\17\1\57\6\17\12\0\1\17\3\0\13\17"+
    "\1\0\6\17\1\60\6\17\1\61\5\17\55\0\1\62"+
    "\2\34\1\0\2\34\1\63\47\34\24\0\1\64\55\0"+
    "\1\65\40\0\1\17\3\0\13\17\1\0\14\17\1\66"+
    "\6\17\12\0\1\17\3\0\13\17\1\0\4\17\1\67"+
    "\16\17\12\0\1\17\3\0\13\17\1\0\13\17\1\70"+
    "\7\17\12\0\1\17\3\0\13\17\1\0\16\17\1\71"+
    "\4\17\12\0\1\17\3\0\13\17\1\0\11\17\1\72"+
    "\11\17\12\0\1\17\3\0\13\17\1\0\14\17\1\73"+
    "\6\17\12\0\1\17\3\0\13\17\1\0\15\17\1\74"+
    "\5\17\12\0\1\17\3\0\13\17\1\0\17\17\1\75"+
    "\3\17\12\0\1\17\3\0\13\17\1\0\7\17\1\76"+
    "\13\17\12\0\1\17\3\0\13\17\1\0\1\77\22\17"+
    "\12\0\1\17\3\0\13\17\1\0\20\17\1\100\2\17"+
    "\12\0\1\17\3\0\13\17\1\0\7\17\1\101\13\17"+
    "\12\0\1\17\3\0\13\17\1\0\7\17\1\102\13\17"+
    "\12\0\1\17\3\0\13\17\1\0\7\17\1\103\13\17"+
    "\27\0\1\104\43\0\1\105\50\0\1\17\3\0\13\17"+
    "\1\0\11\17\1\106\11\17\12\0\1\17\3\0\13\17"+
    "\1\0\1\107\22\17\12\0\1\17\3\0\13\17\1\0"+
    "\17\17\1\110\3\17\12\0\1\17\3\0\13\17\1\0"+
    "\4\17\1\111\16\17\12\0\1\17\3\0\13\17\1\0"+
    "\16\17\1\112\4\17\12\0\1\17\3\0\13\17\1\0"+
    "\1\113\22\17\12\0\1\17\3\0\13\17\1\0\13\17"+
    "\1\114\7\17\12\0\1\17\3\0\13\17\1\0\3\17"+
    "\1\115\17\17\12\0\1\17\3\0\13\17\1\0\4\17"+
    "\1\116\16\17\12\0\1\17\3\0\13\17\1\0\3\17"+
    "\1\117\17\17\12\0\1\17\3\0\13\17\1\0\11\17"+
    "\1\120\11\17\12\0\1\17\3\0\13\17\1\0\17\17"+
    "\1\121\3\17\30\0\1\122\44\0\1\123\46\0\1\17"+
    "\3\0\13\17\1\0\10\17\1\124\12\17\12\0\1\17"+
    "\3\0\13\17\1\0\7\17\1\125\13\17\12\0\1\17"+
    "\3\0\13\17\1\0\4\17\1\126\16\17\12\0\1\17"+
    "\3\0\13\17\1\0\17\17\1\127\3\17\12\0\1\17"+
    "\3\0\13\17\1\0\4\17\1\130\16\17\12\0\1\17"+
    "\3\0\13\17\1\0\4\17\1\131\16\17\26\0\1\132"+
    "\47\0\1\133\45\0\1\17\3\0\13\17\1\0\13\17"+
    "\1\134\7\17\16\0\1\135\67\0\1\136\35\0\1\17"+
    "\3\0\13\17\1\0\20\17\1\137\2\17\31\0\1\140"+
    "\50\0\1\141\41\0\1\17\3\0\13\17\1\0\4\17"+
    "\1\142\16\17\30\0\1\143\46\0\1\144\1\0\1\145"+
    "\57\0\1\146\47\0\1\147\33\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3420];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\4\1\1\11\21\1\1\11"+
    "\3\0\4\11\17\1\1\11\1\1\2\0\16\1\2\0"+
    "\14\1\2\0\6\1\2\0\1\1\2\0\1\1\2\0"+
    "\1\1\2\0\3\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[103];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
  private Parser yyparser;

  public Yylex(java.io.Reader r, Parser yyparser) {
    this(r);
    this.yyparser = yyparser;
    yyline = 1;
  }


  public int getLine() {
      return yyline;
  }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return 0; }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { System.err.println("Error: unexpected character '"+yytext()+"'"); return -1;
            }
            // fall through
          case 32: break;
          case 2:
            { 
            }
            // fall through
          case 33: break;
          case 3:
            { yyline++;
            }
            // fall through
          case 34: break;
          case 4:
            { return (int) yycharat(0);
            }
            // fall through
          case 35: break;
          case 5:
            { yyparser.yylval = new ParserVal(yytext()); 
         return Parser.NUM;
            }
            // fall through
          case 36: break;
          case 6:
            { yyparser.yylval = new ParserVal(yytext());
            return Parser.ID;
            }
            // fall through
          case 37: break;
          case 7:
            { return Parser.NEQ;
            }
            // fall through
          case 38: break;
          case 8:
            { return Parser.AND;
            }
            // fall through
          case 39: break;
          case 9:
            { return Parser.LEQ;
            }
            // fall through
          case 40: break;
          case 10:
            { return Parser.EQ;
            }
            // fall through
          case 41: break;
          case 11:
            { return Parser.GEQ;
            }
            // fall through
          case 42: break;
          case 12:
            { return Parser.IF;
            }
            // fall through
          case 43: break;
          case 13:
            { return Parser.OR;
            }
            // fall through
          case 44: break;
          case 14:
            { yyparser.yylval = new ParserVal(yytext().substring(1, yylength() -1));
	     return Parser.LIT;
            }
            // fall through
          case 45: break;
          case 15:
            { return Parser.FOR;
            }
            // fall through
          case 46: break;
          case 16:
            { return Parser.INT;
            }
            // fall through
          case 47: break;
          case 17:
            { return Parser.BOOL;
            }
            // fall through
          case 48: break;
          case 18:
            { return Parser.ELSE;
            }
            // fall through
          case 49: break;
          case 19:
            { return Parser.MAIN;
            }
            // fall through
          case 50: break;
          case 20:
            { return Parser.READ;
            }
            // fall through
          case 51: break;
          case 21:
            { return Parser.TRUE;
            }
            // fall through
          case 52: break;
          case 22:
            { return Parser.VOID;
            }
            // fall through
          case 53: break;
          case 23:
            { return Parser.BREAK;
            }
            // fall through
          case 54: break;
          case 24:
            { return Parser.FALSE;
            }
            // fall through
          case 55: break;
          case 25:
            { return Parser.FLOAT;
            }
            // fall through
          case 56: break;
          case 26:
            { return Parser.WHILE;
            }
            // fall through
          case 57: break;
          case 27:
            { return Parser.WRITE;
            }
            // fall through
          case 58: break;
          case 28:
            { return Parser.CONTINUE;
            }
            // fall through
          case 59: break;
          case 29:
            { yyparser.setDebug(true);
            }
            // fall through
          case 60: break;
          case 30:
            { yyparser.listarTS();
            }
            // fall through
          case 61: break;
          case 31:
            { yyparser.setDebug(false);
            }
            // fall through
          case 62: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
